### ISSUE TITLE
V-REP_PRO_EDU_V3_5_0_Linux.tar.gz is not available now

### ISSUE THREAD

**Issue by qifeigiao** [luigifreda/3dmr#1]
V-REP_PRO_EDU_V3_5_0_Linux.tar.gz is not available now, Are there alternatives available?https://coppeliarobotics.com/previousVersions has V-REP 3.6.2 but not for ubuntu20.04. Thx！

**Comment by qifeigiao** [comment]
find：https://drive.google.com/file/d/1WIQuVPRsyhX851OL8e21hZMTrqCbX8KN/view?usp=sharing

**Comment by luigifreda** [comment]
Hi,
thanks for your feedback. Glad you found that link. The script `install-vrep.sh` automatically downloads and installs that version of V-REP. I shared a copy of  V-REP 3.5.0 on Google Drive.  See that script for further details: https://github.com/luigifreda/3dmr/blob/main/install-vrep.sh
