### ISSUE TITLE
Error occurred during “catkin build" process for exploration_ws

### ISSUE THREAD

**Issue by Crystal-Biru** [luigifreda/3dmr#2]
Hello! When I run $ ./build_all.sh, a error occured when it comes to exploration_ws. The error massage is shown below:
--------------------------------------------------------------------------------------------------------------------------------
Errors     << rotors_gazebo:make /home/zbr/Projects/3dmr/exploration_ws/logs/rotors_gazebo/build.make.000.log
/bin/sh: 1: python: not found
make[2]: *** [CMakeFiles/sdf.dir/build.make:64: /home/zbr/Projects/3dmr/exploration_ws/src/rotors_simulator/rotors_gazebo/models/iris/iris.sdf] Error 127
make[1]: *** [CMakeFiles/Makefile2:1231: CMakeFiles/sdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Warning at CMakeLists.txt:43 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

CMake Warning at /usr/src/googletest/googletest/CMakeLists.txt:54 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

make: *** [Makefile:141: all] Error 2
cd /home/zbr/Projects/3dmr/exploration_ws/build/rotors_gazebo; catkin build --get-env rotors_gazebo | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................
Failed     << rotors_gazebo:make                        [ Exited with code 2 ] 
Failed    <<< rotors_gazebo                             [ 8.4 seconds ]        
Abandoned <<< rotors_simulator                          [ Unrelated job failed ]
Abandoned <<< interface_nbvp_rotors                     [ Unrelated job failed ]"
--------------------------------------------------------------------------------------------------------------------------------
(I use Ubuntu20.04, ROS noetic, and $ ./install_all.sh is completed successfully.)
Can you help me know how to solve this problem?

**Comment by luigifreda** [comment]
I am not sure why you are getting the following error:
`/bin/sh: 1: python: not found`

Can you try the procedure with `rosdocker` that I suggested here? 
https://github.com/luigifreda/rosdocker#3dmr

**Comment by Crystal-Biru** [comment]
Thank you for your response! I have resolved this issue. I found that the 'rotors_simulator' in 'exploration_ws' was an older version that required a Python environment. I updated 'rotors_simulator' to a new version compatible with Python3, and then successfully ran 'build_all.sh'.
But there is another issue: when I test multi-robot exploration through PyQt GUIs (i.e., ./main.py and ./main_pioneer.py), it seems that there are some errors for UGVs in rviz, and it can not run correctly (shown in the figure). But when I run ./main_pioneer.py, it is successful.
![main](https://github.com/luigifreda/3dmr/assets/60907982/a69083e1-03bb-4ed2-a3b3-a21a084af6fa)
![main_pioneer](https://github.com/luigifreda/3dmr/assets/60907982/e121d322-d456-4276-8797-de5bdd534800)

**Comment by luigifreda** [comment]
I changed a couple of things related to the rotors simulator. If you replace its version in 3dmr, it is expected you hit some issues.

Why don't you try to install the package python-is-python3?
https://askubuntu.com/questions/1296790/python-is-python3-package-in-ubuntu-20-04-what-is-it-and-what-does-it-actually

... or test the rosdocker procedure?

**Comment by Crystal-Biru** [comment]
Thank you for your advice! After installing the package python-is-python3, I successfully run $ ./build_all.sh for your code, but it is curious that when I run ./main.py and ./main_pioneer.py, there is still some error (shown in the following figures), while ./main_jackal.py is ok.
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Crystal-Biru** [comment]
Thank you for your advice! After installing the package python-is-python3, I successfully run $ ./build_all.sh for your original code. However, it is curious that when I run ./main.py and ./main_pioneer.py, there is still some errors (shown in the following figures), while ./main_jackal.py is ok.
![main](https://github.com/luigifreda/3dmr/assets/60907982/29660957-0c93-4a3d-a3ff-392988641580)
![main_pioneer](https://github.com/luigifreda/3dmr/assets/60907982/6340312a-bd80-46d6-81c8-b2be22ccb7bd)
![main_jackal](https://github.com/luigifreda/3dmr/assets/60907982/24b7d592-26cd-458d-9e3e-77ffc4f84a0d)

**Comment by luigifreda** [comment]
Probably, V-REP didn't install correctly. Can you try to get into your working copy folder, remove any "temp" folder, and try to launch again `./install-vrep.sh`? I recently updated the install script (since google changed a bit the cookies management for google drive).  If everything goes well, after that, you should be able to launch `main.py`and `main_pioneer.py`.

**Comment by Crystal-Biru** [comment]
Thank you for your help! I successfully solved this problem!
