### ISSUE TITLE
error occured when running ./compile_with_catkin_build.sh in  exploration_ws

### ISSUE THREAD

**Issue by Zhangguagua** [luigifreda/3dmr#3]
**hello，when I ran the file "./compile_with_catkin_build.sh'' in exploration_ws
a very very very long error message appeared.  It keep saying that"‘mavlink_message_t’ does not name a type; did you mean ‘mavlink_debug_t’?in"hil_interface.h"".But it clearly has been declared, it's really confusing. there is a part of the message below:**
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:319:75: error: ‘mavlink_message_t’ does not name a type; did you mean ‘mavlink_debug_t’?
  319 | static inline uint16_t mavlink_msg_protocol_version_get_max_version(const mavlink_message_t* msg)
      |                                                                           ^~~~~~~~~~~~~~~~~
      |                                                                           mavlink_debug_t
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:329:81: error: ‘mavlink_message_t’ does not name a type; did you mean ‘mavlink_debug_t’?
  329 | static inline uint16_t mavlink_msg_protocol_version_get_spec_version_hash(const mavlink_message_t* msg, uint8_t *spec_version_hash)
      |                                                                                 ^~~~~~~~~~~~~~~~~
      |                                                                                 mavlink_debug_t
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:339:84: error: ‘mavlink_message_t’ does not name a type; did you mean ‘mavlink_debug_t’?
  339 | static inline uint16_t mavlink_msg_protocol_version_get_library_version_hash(const mavlink_message_t* msg, uint8_t *library_version_hash)
      |                                                                                    ^~~~~~~~~~~~~~~~~
      |                                                                                    mavlink_debug_t
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:350:62: error: ‘mavlink_message_t’ does not name a type; did you mean ‘mavlink_debug_t’?
  350 | static inline void mavlink_msg_protocol_version_decode(const mavlink_message_t* msg, mavlink_protocol_version_t* protocol_version)
      |                                                              ^~~~~~~~~~~~~~~~~
      |                                                              mavlink_debug_t
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h: In function ‘void mavlink_msg_protocol_version_decode(const int*, mavlink_protocol_version_t*)’:
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:359:28: error: request for member ‘len’ in ‘* msg’, which is of non-class type ‘const int’
  359 |         uint8_t len = msg->len < MAVLINK_MSG_ID_PROTOCOL_VERSION_LEN? msg->len : MAVLINK_MSG_ID_PROTOCOL_VERSION_LEN;
      |                            ^~~
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:359:76: error: request for member ‘len’ in ‘* msg’, which is of non-class type ‘const int’
  359 |         uint8_t len = msg->len < MAVLINK_MSG_ID_PROTOCOL_VERSION_LEN? msg->len : MAVLINK_MSG_ID_PROTOCOL_VERSION_LEN;
      |                                                                            ^~~
In file included from /opt/ros/noetic/include/mavlink/v2.0/common/../message.hpp:16,
                 from /opt/ros/noetic/include/mavlink/v2.0/common/common.hpp:16,
                 from /opt/ros/noetic/include/mavconn/mavlink_dialect.h:26,
                 from /opt/ros/noetic/include/mavros_msgs/mavlink_convert.h:18,
                 from /home/zfk/Documents/3dmr/exploration_ws/src/rotors_simulator/rotors_hil_interface/include/rotors_hil_interface/hil_interface.h:23,
                 from /home/zfk/Documents/3dmr/exploration_ws/src/rotors_simulator/rotors_hil_interface/src/hil_state_level_interface.cpp:17:
/opt/ros/noetic/include/mavlink/v2.0/common/../mavlink_types.h:157:52: error: request for member ‘payload64’ in ‘* msg’, which is of non-class type ‘const int’
  157 | #define _MAV_PAYLOAD(msg) ((const char *)(&((msg)->payload64[0])))
      |                                                    ^~~~~~~~~
/opt/ros/noetic/include/mavlink/v2.0/common/../standard/../minimal/./mavlink_msg_protocol_version.h:361:30: note: in expansion of macro ‘_MAV_PAYLOAD’
  361 |     memcpy(protocol_version, _MAV_PAYLOAD(msg), len);
      |                              ^~~~~~~~~~~~

I'm using ROS Noetic   Ubuntu 20.04
 I've tried double-checking if all dependencies are installed
 and rebuilding the workspace, but it still don't work. I am feeling a bit desperate, could you please take a look and help me identify what might be causing the issue? Any assistance would be greatly appreciated!

**Comment by luigifreda** [comment]
Hi, 
Thanks for reporting the build error. 
I've just pushed a build fix. 
LMK if it works on your side too.

**Comment by Zhangguagua** [comment]
Thank you so much. It works! I really appreciate your help!
