### ISSUE TITLE
Is there an example script for gazebo simulator ?

### ISSUE THREAD

**Issue by han-kyung-min** [luigifreda/3dmr#4]
Thank you for making this excellent software available to others! 

While studying it, I noticed that there doesn't seem to be an example script for the Gazebo simulator. 
Could you please guide me to it if there is one?

Best regards,

**Comment by luigifreda** [comment]
Hi,
Thanks for the feedback.
I would start studying 
https://github.com/luigifreda/3dmr/blob/main/README.navigation.md
and 
https://github.com/luigifreda/3dmr/blob/main/jackal_ws/src/jackal_3dnav/README.md
You can isolate the components and understand how to use them. Unfortunately, there is not a basic example script. 

All the best,
Luigi
